
- id: postgres_plugin_vip
  type: group
  role: [postgresql_plugin]
  required_for: [deploy_end]
  requires: [deploy_start]
  tasks: [fuel_pkgs, hiera, globals, tools, logging, netconfig,
        hosts, firewall, ssl-keys-saving, ssl-add-trust-chain, hosts, 
        cluster, virtual_ips]
  parameters:
    strategy:
        type: one_by_one

- id: postgres_plugin-deployment
  type: puppet
  version: 2.0.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  requires: [deploy_start, postgres_plugin_vip]
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: "."
    timeout: 3600
    retries: 3

